### ISSUE TITLE
RouteDebug doesn't work as a NuGet package

### ISSUE THREAD

**Issue by bartvanderwalips** [Haacked/RouteMagic#11]
@Haacked, I love your work and your MVC RouteDebugger utility is used a lot, also by me.

However - somewhat strangely - it doesn't quite work as a NuGet package for me. I have only gotten it to work by manually downloading the zipped .dll, adding that to the `/bin` and then adding a reference in my project in Visual Studio. But then of course when I delete my `bin` and `obj` from my project - for instance to fix some obnoxious error in Visual studio when cleaning is not enough - I have to redo this progress.

So I WOULD like to have it as a NuGet packages so it can 'survive a clean'.

For the `RouteDebug` package I get a simple 'does not exist' compile error:

> The type or namespace name 'RouteDebugger' does not exist in the namespace 'RouteDebug' (are you missing an assembly reference?)

This happens on the line

> RouteDebug.RouteDebugger.RewriteRoutesForTesting(RouteTable.Routes);
> that I added in the `Application_Start()` method of `Global.asax.cs`

I have tried removing and re-adding the package as well, but that doesn't help. I am currently using Visual Studio 2013 (Professional): MVC5 (but had this issue in VS 2010 as well).

Note: I logged this as a general issue before, but am now logging this issue on the RouteMagic repo, so I installed this NuGet package (removed the RouteDebugger package first). This gives me a similar error on the same line: 

> The name 'RouteDebug' does not exist in the current context

**Comment by ortrails** [comment]
@Haacked does this work at all with classic web forms?

**Comment by haacked** [comment]
@ortrails it works with Routing. So if you're using Routing with Web Forms, then yes.

**Comment by ortrails** [comment]
@Haacked - thanks for the reply. I was playing around using it for URL rewriting.
        routes.MapPageRoute("rewrite-1",
            "Partner/{page}",
            "~/Admin/{page}");
Value of {page} would be something like "Review.aspx". I guess we should use URL rewrite module for that, right?
